# Generated by Django 4.0.4 on 2022-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prim_nombre', models.CharField(max_length=50)),
                ('seg_nombre', models.CharField(max_length=50)),
                ('prim_apellido', models.CharField(max_length=50)),
                ('seg_apellido', models.CharField(max_length=50)),
                ('dpi', models.IntegerField()),
                ('nit', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=450)),
                ('aldea', models.CharField(max_length=250)),
                ('municipio', models.CharField(max_length=250)),
                ('departamento', models.CharField(max_length=250)),
            ],
        ),
    ]
