# Generated by Django 4.0.4 on 2022-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
