# Generated by Django 4.0.4 on 2022-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(upload_to='images/', verbose_name=''),
        ),
    ]
