# Generated by Django 4.0.4 on 2022-05-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
