# Generated by Django 4.0.4 on 2022-05-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_persona_prim_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion1', models.TextField()),
                ('descripcion2', models.TextField()),
                ('imagen1', models.ImageField(upload_to='images/', verbose_name='')),
                ('imagen2', models.ImageField(upload_to='images/', verbose_name='')),
                ('imagen3', models.ImageField(upload_to='images/', verbose_name='')),
                ('imagen4', models.ImageField(upload_to='images/', verbose_name='')),
                ('imagen5', models.ImageField(upload_to='images/', verbose_name='')),
            ],
        ),
    ]
